# We have a conf and classes directory, add to BBPATH.
BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS:append = " goldvip"
BBFILE_PATTERN_goldvip = "^${LAYERDIR}/"
BBFILE_PRIORITY_goldvip = "11"

# The dynamic-layers directory hosts the extensions and layer specific
# modifications related to NXP products.
#
# The .bbappend and .bb files are included if the respective layer
# collection is available.
BBFILES += "${@' '.join('${LAYERDIR}/dynamic-layers/%s/recipes*/*/*.bbappend' % layer \
                for layer in BBFILE_COLLECTIONS.split())}"
BBFILES += "${@' '.join('${LAYERDIR}/dynamic-layers/%s/recipes*/*/*.bb' % layer \
                for layer in BBFILE_COLLECTIONS.split())}"

# We have recipes-* directories, add to BBFILES.
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

LAYERSERIES_COMPAT_goldvip = "scarthgap"

ALB_RELEASE = "${@d.getVar('RELEASE_BASE').replace('release/','').replace('bsp','').replace('_','')}"
GOLDVIP_RELEASE = "1.16.0"

# This key has to be used within other recipes as well (i.e., TF-A). Create a "global" variable.
GOLDVIP_RSA_PRIVKEY_FILE ?= "${LAYERDIR}/recipes-goldvip/goldvip-bootloader/goldvip-bootloader/rsa_2048_key.pem"